apiVersion: backstage.io/v1alpha1
kind: App
metadata:
  name: goth-cats-application
  annotations:
    github.com/project-slug: TS000/goth-cats
spec:
  type: nextjs
  lifecycle: ninelives
  owner: Wallaby-TS000
annotations:
    backstage.io/techdocs-ref: url:https://github.com/TS000/goth-cats/blob/main/frontend/docs/index.md