---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: goth-cats-mono-repo
  title: Combined Monorepo for Felines of the Night
  description: A combined monorepo
  annotations:
    github.com/project-slug: TS000/goth-cats
    backstage.io/techdocs-ref: dir:.
  tags: 
    - nextjs
    - graphql
spec:
  type: service
  owner: team-wallaby
  lifecycle: experimental