site_name: 'Goth Cats App and API Documentation'
nav:
  - Home: index.md
  - Subdirectory docs:
    - API: '!include ./backend/mkdocs.yml'
    - Frontend: '!include ./frontend/mkdocs.yml'
plugins:
  - monorepo
  - techdocs-core