apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: goth-cats-API
  annotations:
    github.com/project-slug: TS000/goth-cats
annotations:
    backstage.io/techdocs-ref: url:https://github.com/TS000/goth-cats/blob/main/backend/docs/index.md
spec:
  type: graphql
  lifecycle: ninelives
  owner: Wallaby-TS000
  definition: |
    schema {
      query: Root
    }
    """A single Cat Gif"""
    type Gifs implements Node {
      """The title of the cat gif."""
      title: String
      """The link to the cat gif."""
      link: String
      """The id of the gif."""
      id: String
    }