name: Launch the Docs
on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths: [ '/backend/docs/*'' ]
jobs:
  create-techdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Techdocs webhook
        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs-webhook@main
        with:
          repository: ${{ github.repository }}
          descriptor-file: [ backend/catalog-info.yaml ]
          namespace: 'Goth-Cats-API'
          token: ${{ secrets.WEBHOOK_PAT }}